const items = [
  { id: 'big-mac', name: 'Big Mac', price: 2, image: 'images/big-mac.jpg', category: 'Food' },
  { id: 'hot-dog', name: 'Hot Dog', price: 3, image: 'images/hot-dog.jpg', category: 'Food' },
  { id: 'starbucks-coffee', name: 'Starbucks Coffee', price: 5, image: 'images/starbucks-coffee.jpg', category: 'Food' },
  { id: 'movie-ticket', name: 'Movie Ticket', price: 12, image: 'images/movie-ticket.jpg', category: 'Entertainment' },
  { id: 'book', name: 'Book', price: 15, image: 'images/book.jpg', category: 'Entertainment' },
  { id: 'spotify-subscription', name: 'Spotify Subscription (1 Year)', price: 120, image: 'images/spotify-subscription.jpg', category: 'Entertainment' },
  { id: 'netflix-subscription', name: 'Netflix Subscription (1 Year)', price: 180, image: 'images/netflix-subscription.jpg', category: 'Entertainment' },
  { id: 'airpods-pro', name: 'AirPods Pro', price: 249, image: 'images/airpods-pro.jpg', category: 'Electronics' },
  { id: 'nintendo-switch', name: 'Nintendo Switch', price: 299, image: 'images/nintendo-switch.jpg', category: 'Electronics' },
  { id: 'playstation-5', name: 'PlayStation 5', price: 499, image: 'images/playstation-5.jpg', category: 'Electronics' },
  { id: 'xbox-series-x', name: 'Xbox Series X', price: 499, image: 'images/xbox-series-x.jpg', category: 'Electronics' },
  { id: 'smartphone', name: 'High-end Smartphone', price: 1000, image: 'images/smartphone.jpg', category: 'Electronics' },
  { id: 'designer-handbag', name: 'Designer Handbag', price: 2500, image: 'images/designer-handbag.jpg', category: 'Luxury' },
  { id: 'gaming-pc', name: 'High-end Gaming PC', price: 3000, image: 'images/gaming-pc.jpg', category: 'Electronics' },
  { id: 'smart-tv-8k', name: 'Smart TV 8K (85")', price: 5000, image: 'images/smart-tv-8k.jpg', category: 'Electronics' },
  { id: 'massage-chair', name: 'Premium Massage Chair', price: 6000, image: 'images/massage-chair.jpg', category: 'Home' },
  { id: 'hot-tub', name: 'Hot Tub', price: 8000, image: 'images/hot-tub.jpg', category: 'Home' },
  { id: 'family-vacation', name: 'Family Vacation (1 Week)', price: 10000, image: 'images/family-vacation.jpg', category: 'Entertainment' },
  { id: 'jet-ski', name: 'Luxury Jet Ski', price: 12000, image: 'images/jet-ski.jpg', category: 'Entertainment' },
  { id: 'luxury-watch', name: 'Rolex Luxury Watch', price: 15000, image: 'images/luxury-watch.jpg', category: 'Luxury' },
  { id: 'diamond-ring', name: 'Diamond Ring', price: 25000, image: 'images/diamond-ring.jpg', category: 'Luxury' },
  { id: 'bitcoin', name: '1 Bitcoin', price: 65000, image: 'images/bitcoin.jpg', category: 'Investment' },
  { id: 'tesla-model-s', name: 'Tesla Model S Plaid', price: 90000, image: 'images/tesla-model-s.jpg', category: 'Vehicles' },
  { id: 'luxury-suv', name: 'Range Rover Luxury SUV', price: 120000, image: 'images/luxury-suv.jpg', category: 'Vehicles' },
  { id: 'speedboat', name: 'Speedboat', price: 150000, image: 'images/speedboat.jpg', category: 'Vehicles' },
  { id: 'motorhome-rv', name: 'Motorhome RV', price: 200000, image: 'images/motorhome-rv.jpg', category: 'Vehicles' },
  { id: 'ferrari-supercar', name: 'Ferrari Supercar', price: 300000, image: 'images/ferrari-supercar.jpg', category: 'Vehicles' },
  { id: 'space-flight', name: 'Space Flight Ticket', price: 450000, image: 'images/space-flight.jpg', category: 'Entertainment' },
  { id: 'golden-toilet', name: 'Golden Toilet', price: 1000000, image: 'images/golden-toilet.jpg', category: 'Luxury' },
  { id: 'mcdonalds-franchise', name: 'McDonald\'s Franchise', price: 1500000, image: 'images/mcdonalds-franchise.jpg', category: 'Investment' },
  { id: 'luxury-yacht', name: 'Luxury Yacht', price: 15000000, image: 'images/luxury-yacht.jpg', category: 'Luxury' },
  { id: 'formula-1-car', name: 'Formula 1 Car', price: 15000000, image: 'images/formula-1-car.jpg', category: 'Vehicles' },
  { id: 'mansion', name: 'Mansion', price: 25000000, image: 'images/mansion.jpg', category: 'Real Estate' },
  { id: 'private-island', name: 'Private Island', price: 30000000, image: 'images/private-island.jpg', category: 'Real Estate' },
  { id: 'apache-helicopter', name: 'Apache Helicopter', price: 35000000, image: 'images/apache-helicopter.jpg', category: 'Vehicles' },
  { id: 'private-jet', name: 'Private Jet (Gulfstream)', price: 45000000, image: 'images/private-jet.jpg', category: 'Luxury' },
  { id: 'penthouse-nyc', name: 'Penthouse in NYC', price: 50000000, image: 'images/penthouse-nyc.jpg', category: 'Real Estate' },
  { id: 'space-rocket', name: 'SpaceX Falcon 9 Rocket', price: 67000000, image: 'images/space-rocket.jpg', category: 'Vehicles' },
  { id: 'f35-fighter-jet', name: 'F-35 Fighter Jet', price: 90000000, image: 'images/f35-fighter-jet.jpg', category: 'Vehicles' },
  { id: 'super-yacht', name: 'Mega Super Yacht', price: 150000000, image: 'images/super-yacht.jpg', category: 'Luxury' },
  { id: 'skyscraper', name: 'Downtown Skyscraper', price: 850000000, image: 'images/skyscraper.jpg', category: 'Real Estate' },
  { id: 'mona-lisa-painting', name: 'Mona Lisa Painting', price: 850000000, image: 'images/mona-lisa-painting.jpg', category: 'Art' },
  { id: 'mega-cruise-ship', name: 'Mega Cruise Ship', price: 1200000000, image: 'images/mega-cruise-ship.jpg', category: 'Vehicles' },
  { id: 'nba-team', name: 'NBA Basketball Team', price: 3000000000, image: 'images/nba-team.jpg', category: 'Investment' },
  { id: 'nfl-team', name: 'NFL Football Team', price: 4500000000, image: 'images/nfl-team.jpg', category: 'Investment' }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = items;
}
